language: python
cache: pip
branches:
  only:
  - source
python:
- 3.6
install:
- pip install -r requirements.txt
- git config --global user.email "girisagar46@gmail.com"
- git config --global user.name "Sagar Giri"
script:
- fab publish:"Build site"
