language: python
cache: pip
branches:
  only:
  - source
python:
- 3.6
install:
- gem install sass
- pip install -r requirements.txt
- git config --global user.email "girisagar46@gmail.com"
- git config --global user.name "Sagar Giri"
- git clone https://github.com/girisagar46/girisagar46.github.io-theme.git themes/girisagar46.github.io-theme
- git clone --recursive https://github.com/getpelican/pelican-plugins
script:
- fab publish:"Build site"
